### ISSUE TITLE
About the disconnection of the entry

### ISSUE THREAD

**Issue by YuhanMA1** [BigCokee/G14_Encyclopedia#2]
The results of the extracted entries show that 204 to 206 should be combined under the entry "ABASSI"; 
208 and 209 belong to the entry "ABATE", which shows that some of the entries are disconnected and that all the contents of the same entry should be merged together.

**Comment by BigCokee** [comment]
Yes, the content of the same entries should be grouped together so that the original structure of the encyclopedia can be restored.

I formulated the following standards to merge them:
1. If a sentence starts with several consecutive capital letters and then immediately followed by a comma, then it is regarded as the beginning of an entry; 
2. If a sentence does not meet this condition, then it will be considered that the sentence should belong to the previous entry ；

After the standard is established, the regular expression is used to judge and merge.
